import { SpecialEventDefinition } from "../types/index";

export const specialEventsConfig: SpecialEventDefinition[] = [
	{
		name: "180",
		enabled: true,
		detector: "sumLastN",
		params: { n: 3, targetSum: 180 },
		sound: null,
		effects: [
			{ type: "lightshark", executor: { page: 1, column: 6, row: 2 } },
			{ type: "lightshark", executor: { page: 1, column: 7, row: 2 } },
		],
	},
	{
		name: "120",
		enabled: true,
		detector: "consecutivePattern",
		params: { pattern: [60, 60], description: "two triple 20s" },
		sound: "120",
		effects: [],
	},
	{
		name: "one_two_three",
		enabled: true,
		detector: "sequentialSegments",
		params: { segments: [1, 2, 3], multiplier: "single" },
		sound: "one_two_three",
		effects: [],
	},
	{
		name: "three_ones",
		enabled: true,
		detector: "sequentialSegments",
		params: { segments: [1, 1, 1], multiplier: "single" },
		sound: "three_ones",
		effects: [],
	},
	{
		name: "three_sixes",
		enabled: true,
		detector: "sequentialSegments",
		params: { segments: [6, 6, 6], multiplier: "single" },
		sound: "three_sixes",
		effects: [],
	},
	{
		name: "double_oh_seven",
		enabled: true,
		detector: "doubleOhSeven",
		params: { description: "miss, miss, single 7" },
		sound: "double_oh_seven",
		effects: [],
	},
	{
		name: "four_twenty",
		enabled: true,
		detector: "consecutivePattern",
		params: { pattern: [4, 20], description: "single 4 followed by single 20" },
		sound: "four_twenty",
		effects: [],
	},
	{
		name: "thirteen_thirty_seven",
		enabled: true,
		detector: "sequentialSegments",
		params: { segments: [13, 3, 7], multiplier: "single" },
		sound: "thirteen_thirty_seven",
		effects: [],
	},
	{
		name: "triple_seven",
		enabled: true,
		detector: "sequentialSegments",
		params: { segments: [7, 7, 7], multiplier: "single" },
		sound: "triple_seven",
		effects: [],
	},
	{
		name: "sixty_nine",
		enabled: true,
		detector: "consecutivePattern",
		params: { pattern: [6, 9], description: "single 6 followed by single 9" },
		sound: "sixty_nine",
		effects: [],
	},
	{
		name: "one_one_two",
		enabled: true,
		detector: "sequentialSegments",
		params: { segments: [1, 1, 2], multiplier: "single" },
		sound: "one_one_two",
		effects: [],
	},
	{
		name: "nine_one_one",
		enabled: true,
		detector: "sequentialSegments",
		params: { segments: [9, 1, 1], multiplier: "single" },
		sound: "nine_one_one",
		effects: [],
	},
	{
		name: "six_seven",
		enabled: true,
		detector: "consecutivePattern",
		params: { pattern: [6, 7], description: "single 6 followed by single 7" },
		sound: "six_seven",
		effects: [],
	},
	{
		name: "nineteen_oh_four",
		enabled: true,
		detector: "nineteenOhFour",
		params: { description: "single 19, miss, single 4" },
		sound: "nineteen_oh_four",
		effects: [],
	},
	{
		name: "eighteen_eighty_eight",
		enabled: true,
		detector: "sequentialSegments",
		params: { segments: [18, 8, 8], multiplier: "single" },
		sound: "eighteen_eighty_eight",
		effects: [],
	},
	{
		name: "ninety_nine",
		enabled: true,
		detector: "consecutivePattern",
		params: { pattern: [9, 9], description: "two single 9s" },
		sound: "ninety_nine",
		effects: [],
	},
	{
		name: "twenty_one",
		enabled: true,
		detector: "consecutivePattern",
		params: { pattern: [2, 1], description: "single 2 followed by single 1" },
		sound: "twenty_one",
		effects: [],
	},
	{
		name: "twenty_three",
		enabled: true,
		detector: "consecutivePattern",
		params: { pattern: [2, 3], description: "single 2 followed by single 3" },
		sound: "twenty_three",
		effects: [],
	},
	{
		name: "four_oh_four",
		enabled: true,
		detector: "fourOhFour",
		params: { description: "single 4, miss, single 4" },
		sound: "four_oh_four",
		effects: [],
	},
	{
		name: "three_misses",
		enabled: true,
		detector: "consecutiveMisses",
		params: { count: 3 },
		sound: "three_misses",
		effects: [],
	},
];
